// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/daidai53/webook/code/grpc"
	"github.com/daidai53/webook/code/ioc"
	"github.com/daidai53/webook/code/repository"
	"github.com/daidai53/webook/code/repository/cache"
	"github.com/daidai53/webook/code/service"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedisClient()
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewCachedCodeRepository(codeCache)
	smsService := ioc.InitSmsService()
	codeService := service.NewCodeService(codeRepository, smsService)
	codeServiceServer := grpc.NewCodeServiceServer(codeService)
	server := ioc.NewGrpcxServer(codeServiceServer)
	app := &App{
		server: server,
	}
	return app
}
