test:
  key: value1
redis:
  Addr: "localhost:6379"
kafka:
  addr:
    - "localhost:9094"

grpc:
  client:
    inter:
      addr: "localhost:8090"
      secure: false
      threshold: 100
    code:
      addr: "localhost:8091"