test:
  key: value1
redis:
  Addr: "localhost:6379"
kafka:
  addr:
    - "localhost:9094"

grpc:
  client:
    inter:
      addr: "etcd:///service/interactive"
    code:
      addr: "localhost:8091"

etcd:
  addrs:
    - "localhost:12379"